# Generated by Django 4.1 on 2022-09-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0002_fiscales_delete_familiares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscales',
            old_name='nombre_suc',
            new_name='nombre_sucursal',
        ),
        migrations.RenameField(
            model_name='fiscales',
            old_name='nro_serie',
            new_name='numero_serie',
        ),
        migrations.RenameField(
            model_name='fiscales',
            old_name='nro_suc',
            new_name='numero_sucursal',
        ),
    ]
