# Generated by Django 4.1.1 on 2022-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0003_rename_nombre_suc_fiscales_nombre_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscales',
            name='vencimiento_certificado_digital',
            field=models.DateField(blank=True, null=True),
        ),
    ]
